<h1>Welcome to CodeFlow Application Server</h1>

The page you are currently viewing has been served off a CodeFlow Application Server.
<br><br>
CodeFlow is an application server that uses Perl as the driving force behind it.  It is a webserver that is written in Perl, and has database connectivity built into it allowing your applications to utilze a database connection, using authenticated RPC requests to codeflow, and retreive results.  Having said that, while writing applications for CAS, you are able to utiliza a multitude of techniques in order to achive the required results.<br>

<ul>
<li>
Multi-application server.  That means that you can install a number of applications under CAS, and utilize shared resources if required.
</li>

<li>
Session management, CAS will take care of all session management for you.  No, that does not mean authentication, that means that all requests to the CAS server are tracked using a session cookie.
</li>

<li>
Highly configurable.  You can view your current configuration in /etc/codeflow.conf [relative path], and customize as required.
</li>

<li>
CAS is modular, that means that specially written Perl modules can be written for CAS that extend it's functionality.
</li>

<li>
The use of Template Toolkit allows CAS to be very versatile, and a very rapid application development enviroment.
</li>

</ul>

Click on the application menu item above to view what applications have been installed under your CAS, it is fast easy, and we do hope that you enjoy developing under CAS as much as we do!
<br><br>
<b>
The Core CodeFlow Development Team.<br>
</b>
